SELECT
    RIND,
    DENUMIRE,
    '[' || RIND || ']' AS RIND_CHECK,
    '[' || DENUMIRE || ']' AS DENUMIRE_CHECK
FROM CIS2.MD_RIND
WHERE FORM = 49
  AND CAPITOL = 1049
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
 -- AND RIND LIKE '4%'
  AND LENGTH(RIND) > 3
  AND (
        RIND <> TRIM(RIND)
        OR DENUMIRE <> TRIM(DENUMIRE)
      )
ORDER BY ORDINE;


SELECT
    RIND,
    DENUMIRE,
    '[' || RIND || ']' AS RIND_CHECK,
    '[' || DENUMIRE || ']' AS DENUMIRE_CHECK
FROM CIS2.MD_RIND
WHERE FORM = 49
  AND CAPITOL = 1049
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
--   AND RIND LIKE '4%'
  AND LENGTH(RIND) > 3
  AND (
        RIND <> TRIM(RIND)
        OR DENUMIRE <> TRIM(DENUMIRE)
      )
ORDER BY ORDINE;





-- in this case use 
-- this columns 
--ITEM_CODE,
--  ITEM_PARENT,
--  NAME,

SELECT 
  ITEM_CODE_VERS,
  ITEM_CODE,
  ITEM_PARENT,
  NAME,
  SHOW_ORDER,
  SYS_DATE,
  SYS_USER,
  A01      
FROM CIS2.CLS_CLASS_ITEM

WHERE
CLASS_CODE = 'SPEC_3EDU';


SELECT
    ITEM_CODE_VERS,
    ITEM_CODE,
    ITEM_PARENT,
    NAME,
    SHOW_ORDER,
    SYS_DATE,
    SYS_USER,
    A01,
    '[' || ITEM_CODE || ']'   AS ITEM_CODE_CHECK,
    '[' || ITEM_PARENT || ']' AS ITEM_PARENT_CHECK,
    '[' || NAME || ']'        AS NAME_CHECK
FROM CIS2.CLS_CLASS_ITEM
WHERE CLASS_CODE = 'SPEC_2EDU'
  AND (
        ITEM_CODE <> TRIM(ITEM_CODE)
        OR ITEM_PARENT <> TRIM(ITEM_PARENT)
        OR NAME <> TRIM(NAME)
      )
ORDER BY SHOW_ORDER;

UPDATE CIS2.CLS_CLASS_ITEM
SET
    ITEM_CODE   = TRIM(ITEM_CODE),
    ITEM_PARENT = TRIM(ITEM_PARENT),
    NAME        = TRIM(NAME)
WHERE CLASS_CODE = 'SPEC_3EDU'
  AND (
        ITEM_CODE <> TRIM(ITEM_CODE)
        OR ITEM_PARENT <> TRIM(ITEM_PARENT)
        OR NAME <> TRIM(NAME)
      );