SELECT
   DISTINCT  TRIM(SUBSTR(TRIM(RIND),2,30)) RIND_MOD
--    RIND,
--    DENUMIRE,
--    ORDINE
 
FROM CIS2.MD_RIND
WHERE 

  FORM = 49
  AND CAPITOL = 1049
  AND CAPITOL_VERS = 2015
  AND STATUT = '1'
  AND RIND  LIKE '1%'
  AND LENGTH(RIND) > 3
